### ISSUE TITLE
More optimizations should be possible

### ISSUE THREAD

**Issue by ilyaraz** [FALCONN-LIB/FFHT#10]
It turns out that there are some places in the algorithm, which might allow a good amount of optimization. For instance, see the following gist, which has a minimal example.

https://gist.github.com/ilyaraz/4a5d147c1a9cf9cdd25db5e92ee26f17

I realized that I don't understand what is the bottleneck for this code. It also feels like it suffers from more l1 cache misses than necessary.

We should profile and optimize it.

**Comment by ludwigschmidt** [comment]
This roughly corresponds to the later FHT iterations, right? What is surprising about the performance of the code? I guess it might be memory bottlenecks. Did you try to manually prefetch parts of the array?

**Comment by ilyaraz** [comment]
OK,

I redid some measurement which I thought shows that this part is sub-optimal, and apparently I did something wrong before. So, on my machine this code runs in 0.3 s per iteration. The memory bandwidth is 15.8 Gb/s (width 64 bits, 2133 MHz). I guess we come close to the bandwidth bottleneck, right?

**Comment by ilyaraz** [comment]
And yes,

I tried to prefetch, but it has almost no effect.

**Comment by ludwigschmidt** [comment]
The time to scan once through the array is 0.25s, right? So 0.3s is quite
close, yes.

I guess prefetching doesn't help because the memory access pattern is very
predictable.
